#!/usr/bin/env python3
# Copyright 2018 Google LLC
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.
"""Tiny wrapper for t2t-trainer that automatically loads luinet.

Usage:
luinet-server

The server is configured using files; see data/server.conf for an example.
"""

import tensorflow as tf
import genieparser.server.main

def main(argv):
    genieparser.server.main.main(argv)

if __name__ == "__main__":
  tf.app.run()
