package edu.stanford.nlp.sempre.thingtalk;

import java.util.HashMap;
import java.util.Map;

import edu.stanford.nlp.sempre.Value;
import fig.basic.LispTree;

/**
 * Represents a parameter name for thingtalk, with the meta information
 * gathered from the Thingpedia DB
 * 
 * @author Giovanni Campagna
 */
public class ParamNameValue extends Value {
	private final String argname;
	private final String kind;
	private final String type;

	public ParamNameValue(LispTree tree) {
		this.argname = tree.child(1).value;
		this.kind = tree.child(2).value;
		this.type = tree.child(3).value;
	}

	public ParamNameValue(String argname, String kind, String type) {
		this.argname = argname;
		this.kind = kind;
		this.type = type;
	}

	@Override
	public LispTree toLispTree() {
		LispTree tree = LispTree.proto.newList();
		tree.addChild("paramname");
		tree.addChild(argname);
		tree.addChild(kind);
		tree.addChild(type);
		return tree;
	}

	@Override
	public Map<String, Object> toJson() {
		Map<String, Object> json = new HashMap<>();
		// this funky representation is for compat with NameValue
		json.put("id", "tt:param." + argname);
		return json;
	}

	// Generated by Eclipse

	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((argname == null) ? 0 : argname.hashCode());
		result = prime * result + ((kind == null) ? 0 : kind.hashCode());
		result = prime * result + ((type == null) ? 0 : type.hashCode());
		return result;
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj)
			return true;
		if (obj == null)
			return false;
		if (getClass() != obj.getClass())
			return false;
		ParamNameValue other = (ParamNameValue) obj;
		if (argname == null) {
			if (other.argname != null)
				return false;
		} else if (!argname.equals(other.argname))
			return false;
		if (kind == null) {
			if (other.kind != null)
				return false;
		} else if (!kind.equals(other.kind))
			return false;
		if (type == null) {
			if (other.type != null)
				return false;
		} else if (!type.equals(other.type))
			return false;
		return true;
	}
}
